### ISSUE TITLE
Biography plugin is pretty much broken

### ISSUE THREAD

**Issue by PoohBearIRC** [ProgVal/Supybot-plugins#120]
Gives me this error when attempting to read anything: http://pastebin.com/THapwqKn

**Comment by SpiderDave** [comment]
This seems to be the same error I'm getting.  You fixed an error when reloading, but this appears when using get or set after a reload for a channel that already has data.  This probably explains it better:

[20:46] <@SpiderDave> .biography set #foobar SpiderDave email example@example.com
[20:46] <Al> SpiderDave: Sure thing.
[20:47] <@SpiderDave> .biography get #foobar SpiderDave email
[20:47] <Al> SpiderDave: email for SpiderDave: example@example.com
[20:47] <@SpiderDave> .reload Biography
[20:47] <Al> SpiderDave: Sure thing.
[20:47] <@SpiderDave> .biography get #foobar SpiderDave email
[20:47] <Al> SpiderDave: An error has occurred and has been logged. Check the logs for more information.
[20:47] <@SpiderDave> .biography set #foobar SpiderDave email example@example.com
[20:47] <Al> SpiderDave: An error has occurred and has been logged. Check the logs for more information.

INFO 2015-12-19T20:46:50 biography set called on #test by "SpiderDave!HydraIRC@b
est.server.name.ever".
INFO 2015-12-19T20:47:00 biography get called on #test by "SpiderDave!HydraIRC@b
est.server.name.ever".
INFO 2015-12-19T20:47:04 reload called on #test by "SpiderDave!HydraIRC@best.ser
ver.name.ever".
INFO 2015-12-19T20:47:08 biography get called on #test by "SpiderDave!HydraIRC@b
est.server.name.ever".
ERROR 2015-12-19T20:47:08 Spec: [<context for channel>, <first for ('otherUser',
 'user')>, <optional for something>]
ERROR 2015-12-19T20:47:08 Received args: []
ERROR 2015-12-19T20:47:08 Extra args: ['channel', 'user', 'key']
ERROR 2015-12-19T20:47:08 Uncaught exception in ['biography', 'get'].
Traceback (most recent call last):
  File "C:\PYTHON27\lib\site-packages\supybot\callbacks.py", line 1268, in _call
Command
    self.callCommand(command, irc, msg, *args, **kwargs)
  File "C:\PYTHON27\lib\site-packages\supybot\utils\python.py", line 91, in g
    f(self, *args, **kwargs)
  File "C:\PYTHON27\lib\site-packages\supybot\callbacks.py", line 1249, in callC
ommand
    method(irc, msg, *args, **kwargs)
  File "C:\PYTHON27\lib\site-packages\supybot\commands.py", line 1079, in newf
    f(self, irc, msg, args, *state.args, **state.kwargs)
  File "J:\Limnoria\al\plugins\Biography\plugin.py", line 113, in get
    'value': info[key]})
TypeError: string indices must be integers, not str
ERROR 2015-12-19T20:47:08 Exception id: 0x7347f
INFO 2015-12-19T20:47:13 biography set called on #test by "SpiderDave!HydraIRC@b
est.server.name.ever".
ERROR 2015-12-19T20:47:13 Uncaught exception in ['biography', 'set'].
Traceback (most recent call last):
  File "C:\PYTHON27\lib\site-packages\supybot\callbacks.py", line 1268, in _call
Command
    self.callCommand(command, irc, msg, *args, **kwargs)
  File "C:\PYTHON27\lib\site-packages\supybot\utils\python.py", line 91, in g
    f(self, *args, **kwargs)
  File "C:\PYTHON27\lib\site-packages\supybot\callbacks.py", line 1249, in callC
ommand
    method(irc, msg, *args, **kwargs)
  File "C:\PYTHON27\lib\site-packages\supybot\commands.py", line 1079, in newf
    f(self, irc, msg, args, *state.args, **state.kwargs)
  File "J:\Limnoria\al\plugins\Biography\plugin.py", line 139, in set
    self.db[channeluser].update({key: value})
AttributeError: 'str' object has no attribute 'update'
ERROR 2015-12-19T20:47:13 Exception id: 0x8ce36
