### ISSUE TITLE
GeekQuote plugin broken by py3

### ISSUE THREAD

**Issue by truexfan81** [ProgVal/Supybot-plugins#142]
traceback:

INFO 2013-10-27T01:56:12 geekquote called on ##truexfan81 by
     "truexfan81!truexfan81@gateway/shell/cadoth.net/x-myrxaycvrguzydyh".
ERROR 2013-10-27T01:56:12 Spec: [<additional for ('id', 'geekquote')>]
ERROR 2013-10-27T01:56:12 Received args: []
ERROR 2013-10-27T01:56:12 Extra args: ['id']
ERROR 2013-10-27T01:56:12 Uncaught exception in ['geekquote'].
Traceback (most recent call last):
  File "/usr/lib/python3.3/site-packages/supybot/callbacks.py", line 1264, in _callCommand
    self.callCommand(command, irc, msg, *args, **kwargs)
  File "/usr/lib/python3.3/site-packages/supybot/utils/python.py", line 86, in g
    f(self, *args, **kwargs)
  File "/usr/lib/python3.3/site-packages/supybot/plugins/GeekQuote/plugin.py", line 64, in callCommand
    self.__parent.callCommand(method, irc, msg, *L, **kwargs)
  File "/usr/lib/python3.3/site-packages/supybot/utils/python.py", line 86, in g
    f(self, *args, **kwargs)
  File "/usr/lib/python3.3/site-packages/supybot/callbacks.py", line 1245, in callCommand
    method(irc, msg, *args, **kwargs)
  File "/usr/lib/python3.3/site-packages/supybot/commands.py", line 1074, in newf
    f(self, irc, msg, args, *state.args, **state.kwargs)
  File "/usr/lib/python3.3/site-packages/supybot/plugins/GeekQuote/plugin.py", line 214, in geekquote
    self._gkBackend(irc, msg, site, id)
  File "/usr/lib/python3.3/site-packages/supybot/plugins/GeekQuote/plugin.py", line 100, in _gkBackend
    quote = self._gkFetchData(site, id, random=True)
  File "/usr/lib/python3.3/site-packages/supybot/plugins/GeekQuote/plugin.py", line 179, in _gkFetchData
    for item in self._gkREDict[site].finditer(html):
TypeError: can't use a string pattern on a bytes-like object
ERROR 2013-10-27T01:56:12 Exception id: 0x14e45

**Comment by GLolol** [comment]
This plugin doesn't exist anymore; it looks like was removed in 52f814f4ac088e602cdcbde87998b16e989df6b2. (strangely, 6 months before this issue was filed?!?!)
