### ISSUE TITLE
Twitter tests are failing

### ISSUE THREAD

**Issue by Mikaela** [ProgVal/Supybot-plugins#177]
```
% supybot-test Twitter
Failed to load plugin Twitter:Traceback (most recent call last):
  File "/home/mikaela/.local/bin/supybot-test", line 200, in <module>
    pluginModule = plugin.loadPluginModule(pluginName)
  File "/home/mikaela/.local/lib/python2.7/site-packages/supybot/plugin.py", line 65, in loadPluginModule
    module = imp.load_module(name, *moduleInfo)
  File "./Twitter/__init__.py", line 57, in <module>
    from . import plugin
  File "./Twitter/plugin.py", line 69, in <module>
    raise callbacks.Error('You need the python-twitter library.')
Error: You need the python-twitter library.
(pluginDirs: ['.'])
Testing began at Sun May 25 14:28:30 2014 (pid 22185)

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
```

```
% pip freeze|grep twitter
Warning: cannot find svn location for apsw==3.8.2-r1
python-twitter==1.3.1
twitter==1.14.3
```

**Comment by traumschule** [comment]
Same.
```
 $ pip freeze|grep twitter
python-twitter==3.5
twitter==1.18.0
$ torsocks supybot-test Twitter
/home/traumschule/.local/lib64/python3.6/site-packages/supybot/plugin.py:32: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Failed to load plugin Twitter:Traceback (most recent call last):
  File ".local/bin/supybot-test", line 205, in <module>
    pluginModule = plugin.loadPluginModule(pluginName)
  File ".local/lib64/python3.6/site-packages/supybot/plugin.py", line 62, in loadPluginModule
    raise ImportError(name)
ImportError: Twitter
(pluginDirs: ['.'])
Testing began at Fri Dec 14 21:48:20 2018 (pid 6301)

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
```

**Comment by ProgVal** [comment]
@traumschule The error you get means that it could not find the plugin.

**Comment by traumschule** [comment]
According to pip it is installed, no?
> $ pip install Twitter --user
> Requirement already satisfied: Twitter in .local/lib64/python3.6/site-packages (1.18.0)

**Comment by ProgVal** [comment]
That's a twitter library, not a limnoria plugin
