### ISSUE TITLE
[GitHub] Service timeout after requesting webhook test payload

### ISSUE THREAD

**Issue by Poorchop** [ProgVal/Supybot-plugins#225]
I can't receive any notifications from GitHub whatsoever via webhooks, as my bot won't even accept the initial test payload. Here is the traceback:

``` bash
INFO 2014-09-07T02:54:26 Got ping event from GitHub.
INFO 2014-09-07T02:54:31 HTTP request: 192.30.252.41 - "POST /github HTTP/1.1"
     200 -
ERROR 2014-09-07T02:54:31 Uncaught exception in GithubCallback.doPost:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/supybot/log.py", line 361, in m
    return f(self, *args, **kwargs)
  File "/home/poorchop/runbot/plugins/GitHub/plugin.py", line 137, in doPost
    self.send_response(200)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 393, in send_response
    (self.protocol_version, code, message))
  File "/usr/lib/python2.7/socket.py", line 324, in write
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
ERROR 2014-09-07T02:54:31 Exception id: 0x51f87
----------------------------------------
Exception happened during processing of request from ('192.30.252.41', 54738)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 651, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 704, in finish
    self.wfile.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------
```

I'm using the latest version of the GitHub plugin. The webserver at the port I have specified loads up properly, and the GitHub plugin itself loads without any issues. I'm running this on Debian 7.

**Comment by nyuszika7h** [comment]
I just started getting the same issue, although for me, it started happening since I made some modifications to the plugin that I plan to PR.

There is no error in my logs; the bot announces all the commits, but with a 10-second delay between them. `protocols.irc.throttleTime` is set to `1.0`. The latency is 0.07 seconds.

**Comment by its-saurabhjain** [comment]
Similar timeout issue while integrating with Jenkins and Github. I used Jenkins GitHub plugin and configured to manage the webhook. However when i push the code to Github , getting the same service timeout issue...looking for a resolution

**Comment by ProgVal** [comment]
@its-saurabhjain This repo contains plugins for the Supybot/Limnoria IRC bot. Is this what you are having issues with?
