### ISSUE TITLE
git.io URL shortening is broken

### ISSUE THREAD

**Issue by nyuszika7h** [ProgVal/Supybot-plugins#260]
```
ERROR 2015-01-07T21:02:48 Cannot connect to git.io: HTTP Error 422: Unprocessable Entity
```

**Comment by Dozodouzo** [comment]
I'm having the same issue. Any chance on this getting fixed or at least a work around that doesn't grab a shortened url?

```
INFO 2015-02-13T00:34:33 supybot HTTP request: 192.30.252.42 - "POST /github HTTP/1.1" 200 -
ERROR 2015-02-13T00:34:37 supybot Cannot connect to git.io: HTTP Error 422: Unprocessable Entity
ERROR 2015-02-13T00:34:37 supybot Uncaught exception in GithubCallback.doPost:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/supybot/log.py", line 361, in m
    return f(self, *args, **kwargs)
  File "/home/pi/runbot/plugins/lolhub/plugin.py", line 146, in doPost
    self.plugin.announce.onPayload(headers, json.loads(form['payload'].value))
  File "/home/pi/runbot/plugins/lolhub/plugin.py", line 310, in onPayload
    'push', hidden)
  File "/home/pi/runbot/plugins/lolhub/plugin.py", line 229, in _createPrivmsg
    repl[key + '__branch'] = value.split('/', 2)[2]
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by w1sht0l1v3** [comment]
https://github.com/ProgVal/Supybot-plugins/blob/master/GitHub/plugin.py#L217
change into if key.endswith('commit__url'):

**Comment by ProgVal** [comment]
Same comment as https://github.com/ProgVal/Supybot-plugins/issues/273#issuecomment-92509893
