### ISSUE TITLE
stop editing IMDb here and use my repo please

### ISSUE THREAD

**Issue by ddan39** [ProgVal/Supybot-plugins#302]
This is getting annoying... people complain to me, but they are using an old copy of my plugin that has been edited. If you want to fix something... make a pull request or issue on my repo. The last edits @horstderheld made here were to fix things 2 months after I had already fixed them in my repo... lol

I have also recoded most of the plugin... and it now has fully customizable output with config settings.

I am on freenode 24/7 as Dan39 and should reply within 24 hours, just query me. Thanks

**Comment by ProgVal** [comment]
Could you add Python 3 support first?

```
 progval@ion  ~/irc/IMDb   master  supybot-test IMDb                                             
Failed to load plugin IMDb:Traceback (most recent call last):
  File "/home/progval/.local/bin/supybot-test", line 200, in <module>
    pluginModule = plugin.loadPluginModule(pluginName)
  File "/home/progval/.local/lib/python3.4/site-packages/supybot/plugin.py", line 65, in loadPluginModule
    module = imp.load_module(name, *moduleInfo)
  File "/usr/lib/python3.4/imp.py", line 245, in load_module
    return load_package(name, filename)
  File "/usr/lib/python3.4/imp.py", line 217, in load_package
    return methods.load()
  File "<frozen importlib._bootstrap>", line 1220, in load
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "./IMDb/__init__.py", line 31, in <module>
    import plugin
ImportError: No module named 'plugin'
```

**Comment by ddan39** [comment]
Ah, I did add python 3 support long ago, but did not make the changes to
test.py Will have to do that also I guess... Didnt think test.py was
important :P

**Comment by ProgVal** [comment]
er, the problem is in `__init__.py`.

**Comment by ddan39** [comment]
Right, sorry got mixed up since I saw you make changes in __init__.py and
test.py for the testing stuff; assumed wrong...

I just copied over your changes for both __init__.py and test.py. Hopefully
everything is good now. I don't have py3 bot up atm to test with.

**Comment by ProgVal** [comment]
You could import the test, by the way

**Comment by ddan39** [comment]
fyi everything is fixed i believe. i have not tested it on python 3 though

and i did add the same test import that you did to __init__.py

**Comment by ProgVal** [comment]
> fyi everything is fixed i believe.

```
======================================================================
FAIL: testSearch (IMDb.test.IMDbTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/progval/.local/lib/python3.4/site-packages/supybot/test.py", line 191, in runTest
    originalRunTest()
  File "./IMDb/test.py", line 16, in testSearch
    '\x02\x031,8IMDb\x03 http://www.imdb.com/title/tt3061046/')
  File "/home/progval/.local/lib/python3.4/site-packages/supybot/test.py", line 367, in assertResponse
    '%r != %r' % (expectedResponse, m.args[1]))
AssertionError: "Error: AttributeError: 'dict' object has no attribute 'iteritems'" != '\x02\x031,8IMDb\x03 http://www.imdb.com/title/tt3061046/'
- Error: AttributeError: 'dict' object has no attribute 'iteritems'
+ 1,8IMDb http://www.imdb.com/title/tt3061046/
 : '\x02\x031,8IMDb\x03 http://www.imdb.com/title/tt3061046/' != "Error: AttributeError: 'dict' object has no attribute 'iteritems'"

```

> i have not tested it on python 3 though

```
pip uninstall limnoria
pip3 install limnoria --user
supybot-test IMDb/

**Comment by ddan39** [comment]
fixed
