### ISSUE TITLE
Trivia bot won't recognize answers?

### ISSUE THREAD

**Issue by braimee** [ProgVal/Supybot-plugins#306]
Hey all,

I got the Trivia bot up and going and made a question list and all that - which works GREAT.  However, even when people say the right answer in the channel, the bot won't recognize it.  I tailed the messages.log for the bot, and this seems like it could be the culprit.  

>ERROR 2016-09-23T16:26:35 supybot Uncaught exception in Trivia.__call__:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/supybot/log.py", line 363, in m
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/supybot/irclib.py", line 132, in __call__
    method(irc, msg)
  File "/home/brian/bot/plugins/Trivia/plugin.py", line 89, in doPrivmsg
    self.games[channel].answer(msg)
  File "/home/brian/bot/plugins/Trivia/plugin.py", line 221, in answer
    dist = self.DL(str.lower(msg.args[1]), str.lower(ans))
  File "/home/brian/bot/plugins/Trivia/plugin.py", line 257, in DL
    thisrow = range(1, len(seq2) + 1) + [0]
TypeError: unsupported operand type(s) for +: 'range' and 'list'
ERROR 2016-09-23T16:26:35 supybot Exception id: 0x6545

Any ideas?

Thanks,
Brian

**Comment by ProgVal** [comment]
Fixed by commit 248a849b3ebd8ecf72810a7fed29ad1afc2e9bf4.

**Comment by braimee** [comment]
That fixed it - thanks for the super SUPER fast response!

**Comment by braimee** [comment]
Hi there,

Sorry for the trouble but with the new fix, the bot *does* recognize when people answer correctly, however, once they submit a correct answer the module crashes with the error below, and no further questions will appear in the round:

>ERROR 2016-09-23T22:53:03 supybot Uncaught exception in Trivia.__call__:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/supybot/log.py", line 363, in m
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/supybot/irclib.py", line 132, in __call__
    method(irc, msg)
  File "/home/brian/bot/plugins/Trivia/plugin.py", line 89, in doPrivmsg
    self.games[channel].answer(msg)
  File "/home/brian/bot/plugins/Trivia/plugin.py", line 238, in answer
    self.writeScores()
  File "/home/brian/bot/plugins/Trivia/plugin.py", line 248, in writeScores
    scores = self.scores.iteritems()
AttributeError: 'dict' object has no attribute 'iteritems'
ERROR 2016-09-23T22:53:03 supybot Exception id: 0x54b6a

**Comment by ProgVal** [comment]
Ooops, sorry.
Fixed in 1475cfc.

**Comment by braimee** [comment]
Works like a champ now, thanks again!
