### ISSUE TITLE
trivia supybot Uncaught exception in ['start']

### ISSUE THREAD

**Issue by sacredland** [ProgVal/Supybot-plugins#328]
INFO 2019-08-01T01:27:09 supybot start called on #Trivia by "tabb!tabb@*".
ERROR 2019-08-01T01:27:09 supybot Uncaught exception in ['start'].
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/supybot/callbacks.py", line 1319, in _callCommand
    self.callCommand(command, irc, msg, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/supybot/utils/python.py", line 90, in g
    f(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/supybot/callbacks.py", line 1285, in callCommand
    method(irc, msg, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/supybot/commands.py", line 1104, in newf
    f(self, irc, msg, args, *state.args, **state.kwargs)
  File "/home/trivia/Limnoria/plugins/Trivia/plugin.py", line 300, in start
    self.games[channel] = self.Game(irc, channel, num, self)
  File "/home/trivia/Limnoria/plugins/Trivia/plugin.py", line 112, in __init__
    line = f.readline()
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 458: ordinal not in range(128)
ERROR 2019-08-01T01:27:09 supybot Exception id: 0x657c0

**Comment by ProgVal** [comment]
Hi, thanks for the report. I just pushed a fix, tell me if it doesn't work.
